// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Task_managemant_web_API.Data;

#nullable disable

namespace Task_managemant_web_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250129115801_add-user-stickeynotes-colors-with-thier-relations")]
    partial class adduserstickeynotescolorswiththierrelations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Task_managemant_web_API.Models.Color", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("ColorCode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Colors", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ColorCode = "#FF6B6B"
                        },
                        new
                        {
                            Id = 2,
                            ColorCode = "#4ECDC4"
                        },
                        new
                        {
                            Id = 3,
                            ColorCode = "#96CEB4"
                        },
                        new
                        {
                            Id = 4,
                            ColorCode = "#FFEEAD"
                        },
                        new
                        {
                            Id = 5,
                            ColorCode = "#D4A5A5"
                        });
                });

            modelBuilder.Entity("Task_managemant_web_API.Models.StickyNote", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("ColorID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoteDescription")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ColorID")
                        .IsUnique();

                    b.HasIndex("UserID");

                    b.ToTable("StickyNotes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ColorID = 1,
                            CreatedAt = new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NoteDescription = "I am Jose Morinho",
                            UserID = 1
                        },
                        new
                        {
                            Id = 2,
                            ColorID = 2,
                            CreatedAt = new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NoteDescription = "I am Ahmed Babader",
                            UserID = 1
                        },
                        new
                        {
                            Id = 3,
                            ColorID = 3,
                            CreatedAt = new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NoteDescription = "I am Salim Mohammed",
                            UserID = 1
                        },
                        new
                        {
                            Id = 4,
                            ColorID = 4,
                            CreatedAt = new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NoteDescription = "I am Ali Ammar",
                            UserID = 1
                        });
                });

            modelBuilder.Entity("Task_managemant_web_API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "ahmed@gmail.com",
                            Image = "asfjhkjnbvm",
                            Password = "123",
                            UserName = "Ahmed Babder"
                        });
                });

            modelBuilder.Entity("Task_managemant_web_API.Models.StickyNote", b =>
                {
                    b.HasOne("Task_managemant_web_API.Models.Color", "Color")
                        .WithOne("StickyNote")
                        .HasForeignKey("Task_managemant_web_API.Models.StickyNote", "ColorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Task_managemant_web_API.Models.User", "User")
                        .WithMany("stickyNotes")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Color");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Task_managemant_web_API.Models.Color", b =>
                {
                    b.Navigation("StickyNote");
                });

            modelBuilder.Entity("Task_managemant_web_API.Models.User", b =>
                {
                    b.Navigation("stickyNotes");
                });
#pragma warning restore 612, 618
        }
    }
}
